version: '3.8'

services:
  backend:
    build: ./backend
    container_name: retrocloud_backend
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./backend/static:/app/static
      - ./backend/database.db:/app/instance/database.db
      - ./emulatorjs/roms:/emulatorjs/roms
    networks:
      - retrocloud

  nginx:
    image: nginx:alpine
    container_name: retrocloud_nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./frontend2:/var/www/frontend:ro
      - ./emulatorjs/roms:/emulatorjs/roms:ro
    depends_on:
      - backend
    networks:
      - retrocloud

networks:
  retrocloud:
    driver: bridge
